### ISSUE TITLE
CRC Calculation

### ISSUE THREAD

**Issue by petertumfart** [retrospy/OPT4048#1]
Hi, great repo, thank you for sharing it!

Do you have an idea how to perform the crc calculation?
The datasheet does not lead me anywhere ^^

Best,
Peter

**Comment by zoggins** [comment]
I haven't played with it much to verify, but here is what the datasheet says is (this is for channel 0):
CRC bits CH0.
R[19:0]=(RESULT_MSB_CH0[11:0]<<8)+RESULT_LSB_C
H0[7:0]
X[0]=XOR(EXPONENT_CH0[3:0],R[19:0],CRC_CH0[3:0])
XOR of all bits
X[1]=XOR(CRC_CH0[1],CRC_CH0[3],R[1],R[3],R[5],R[7],
R[9],R[11],R[13],R[15],R[17],R[19],E[1],E[3])
X[2]=XOR(CRC_CH0[3],R[3],R[7],R[11],R[15],R[19],E[3])
X[3]=XOR(R[3],R[11],R[19])

I wasn't using it so I haven't exposed counter and CRC in the library , but I think I will add it.

**Comment by zoggins** [comment]
Well I am questioning the datasheet, because I cannot replicate their checksum numbers.  I doubt I am having this much actual checksum failures :)  I have checked my results by hand, by calculator and by code and I cannot 100% duplicate their checksums.

**Comment by zoggins** [comment]
The datasheet is wrong.  The CRC should not require the CRC value as part of the calculation.  They meant Counter.  I will post the code once I clean it up.

**Comment by zoggins** [comment]
Here is the code.  With my Teensy 4.0, 10k pullup resisters on SCL and SDA, and a variety of different wires I get about a 0.05% CRC failure rate.  That is low enough that I am convinced I am calculating it correctly, but higher than I would have expected.  I might try some other boards out of curiosity.

	byte CalculateCRC()
	{
		byte crc = 0;

		crc = CalculateParity(rawResult.Exponent, 0, 1, 4) ^ CalculateParity(rawResult.Mantissa, 0, 1, 20) ^ CalculateParity(Counter, 0, 1, 4);
		crc |= ((CalculateParity(rawResult.Exponent, 1, 2, 4) ^ CalculateParity(rawResult.Mantissa, 1, 2, 20) ^ CalculateParity(Counter, 1, 2, 4)) << 1);
		crc |= ((CalculateParity(rawResult.Exponent, 3, 4, 4) ^ CalculateParity(rawResult.Mantissa, 3, 4, 20) ^ CalculateParity(Counter, 3, 4, 4)) << 2);
		crc |= (CalculateParity(rawResult.Mantissa, 3, 8, 20) << 3);

		return crc;
	}


	byte CalculateParity(int value, int start, int step, byte bytes)
	{
		byte result;
		for(int i = start; i < bytes; i += step)
		{
			if (i == start)
				result = (value & (1 << i)) == 0 ? 0 : 1;
			else
				result ^= (value & (1 << i)) == 0 ? 0 : 1;
		}
		return result;
	}
};

**Comment by petertumfart** [comment]
Nice, thank you!

**Comment by petertumfart** [comment]
Hi,
I tried it on an Arduino Mega and also got some CRC failures. When i digged further, this seemed only to happen for a mantissa greater than 65535, i.e. 2^16. However, all variables should be allocated big enough and it seemed that the bit operation in calculateParity() didnt work anymore. So I changed `result = (value & (1 << i)) == 0 ? 0 : 1;` to `result ^= (value >> i) & 1;`. After that I got no more crc failures.

**Comment by petertumfart** [comment]
```
int CalculateParity(uint32_t value, int start, int step, int bytes){
    int result;
    for(int i = start; i < bytes; i += step){
        if (i == start){
            result = (value >> i) & 1; 
        }
	else{
            result ^= (value >> i) & 1;
        }
    }
    return result;
}
```

**Comment by zoggins** [comment]
Awesome!  I will test myself and get the library updated.  That is weird though, but if it works :)

**Comment by zoggins** [comment]
Oddly this doesn't seem to change my CRC failure %.  I am thinking something might be wrong with my circuit, but I would expect some improvement.

**Comment by zoggins** [comment]
I updated the calculateparity function because yours is correct when handling big mantissas, however my setup is still reporting .05% CRC errors.  When I tried a Mega it was actually worse, more like .6%.  It must be my breadboard or something, its still a mystery.

**Comment by petertumfart** [comment]
Thank you for updating it :)
The big mantissa issue may be just board specific. As the ATMega-based boards store integers by default as 2-byte (16bit) integers. Therefore, typecasting the `1` to `uint32_t` works as well: `result = (value & ((uint32_t)(1) << i)) == 0 ? 0 : 1;`

**Comment by zoggins** [comment]
This should be good now
